module.exports = [
    {title: "Álgebra", value:830, image:"img.jpg"},
    {title: "Universidades", value:1150, image:"img.jpg"},
    {title: "Heliocentrismo", value:1543, image:"img.jpg"},
    {title: "Lunas de Júpiter", value:1609, image:"img.jpg"},
    {title: "Logaritmos", value:1614, image:"img.jpg"},
    {title: "Leyes de Kepler", value:1619, image:"img.jpg"},
    {title: "Barómetro", value:1643, image:"img.jpg"},
    {title: "Reloj de péndulo", value:1656, image:"img.jpg"},
    {title: "Telescopio Newtoniano", value:1668, image:"img.jpg"},
    {title: "Cálculo infinitesimal", value:1675, image:"img.jpg"},
    {title: "Velocidad de la luz", value:1676, image:"img.jpg"},
    {title: "Máquina de vapor", value:1712, image:"img.jpg"},
    {title: "Máquina de vapor", value:1712, image:"img.jpg"},
    {title: "Termómetro de mercurio", value:1714, image:"img.jpg"},
    {title: "Escala Celsius", value:1742, image:"img.jpg"},
    {title: "Condensador", value:1745, image:"img.jpg"},
    {title: "Barco a vapor", value:1783, image:"img.jpg"},
    {title: "Sistema métrico", value:1795, image:"img.jpg"},
    {title: "Vacuna", value:1796, image:"img.jpg"},
    {title: "Litio", value:1817, image:"img.jpg"},
    {title: "Efecto Doppler", value:1845, image:"img.jpg"},
    {title: "Tabla periódica", value:1869, image:"img.jpg"},
    {title: "Rayos catódicos", value:1875, image:"img.jpg"},
    {title: "Bombilla", value:1879, image:"img.jpg"},
    {title: "Rayos X", value:1895, image:"img.jpg"},
    {title: "Electrón", value:1897, image:"img.jpg"}
];
